### PR TITLE
JSXGraph Library

### PR DESCRIPTION
**Pull request by gksander**
JSXGraph Assessment Library. Still unsure on how to best hook the JS
code produced into the question so that it is non-blocking

### CODE REVIEW

**Comment by gksander** [comment]
(This is my first ever git/github experience - so I apologize in advance for my noob-ness.)

**Comment by drlippman** [comment]
Sorry - I got caught up in some other stuff and totally forgot about this. I'll take a look again and see if I can come up with a good solution for the JS hook.

**Comment by gksander** [comment]
No worries - I also got caught up in other stuff, and just now thought about this this morning.

The JS code for the hook is at the end of the JSXG_createAxes() (line 166) and JSXG_createPolarAxes() (line 1043)

**Comment by drlippman** [comment]
I rewrote the script call to first look and see if it's already been loaded, and that seems to be working.  I also changed the call to makeBoard to use the system's `initstack` script loading stack, which prevents race conditions (where the board was being initialized before MathJax was ready).  Going to merge this in.

**Pull request merged**
